- name: Download binutils-{{ psptoolchain_binutils_version }}
  get_url:
    url=ftp://ftp.gnu.org/pub/gnu/binutils/binutils-{{ psptoolchain_binutils_version }}.tar.bz2
    dest={{ psptoolchain_tmp_path }}/

- name: Extract binutils-{{ psptoolchain_binutils_version }}
  unarchive:
    src={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}.tar.bz2
    dest={{ psptoolchain_tmp_path }}
    copy=no

- name: Apply binutils-{{ psptoolchain_binutils_version }}-PSP patch
  patch:
    src=binutils-{{ psptoolchain_binutils_version }}-PSP.patch
    basedir={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}
    strip=1

- name: Apply binutils-{{ psptoolchain_binutils_version }}-texinfofix patch
  patch:
    src=binutils-{{ psptoolchain_binutils_version }}-texinfofix.patch
    basedir={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}
    strip=1

- name: Create build directory
  file: path={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}/build-{{ target }} state=directory

- name: Configure binutils-{{ psptoolchain_binutils_version }}
  shell: chdir={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}/build-{{ target }} CFLAGS="$CFLAGS -I/opt/local/include -Wno-error" CPPFLAGS="$CPPFLAGS -I/opt/local/include -Wno-error" LDFLAGS="$LDFLAGS -L/opt/local/lib" ../configure --prefix="{{ install_dir }}" --target="{{ target }}" --enable-install-libbfd

- name: Compile binutils-{{ psptoolchain_binutils_version }}
  shell: chdir={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}/build-{{ target }} make -j {{ ansible_processor_vcpus }} clean &&  make -r -j {{ ansible_processor_vcpus }}

- name: Install binutils-{{ psptoolchain_binutils_version }}
  sudo: yes
  shell: chdir={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }}/build-{{ target }} make -j {{ ansible_processor_vcpus }} install

- name: Clean binutils-{{ psptoolchain_binutils_version }}
  file: path={{ psptoolchain_tmp_path }}/binutils-{{ psptoolchain_binutils_version }} state=absent
