# tasks file for psplinkusb
- name: Download PSP eboot signer
  git: repo=git://github.com/int-0/ebootsigner
       dest={{ psptoolchain_tmp_path }}/ebootsigner
       accept_hostkey=yes

- name: Compile PSP eboot signer
  shell: chdir={{ psptoolchain_tmp_path }}/ebootsigner make -j {{ ansible_processor_vcpus }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"

- name: Install PSP eboot signer
  shell: chdir={{ psptoolchain_tmp_path }}/ebootsigner make -j {{ ansible_processor_vcpus }} install
  sudo: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"

- name: Clean PSP eboot signer
  file: path={{ psptoolchain_tmp_path }}/ebootsigner state=absent
