# tasks file for psplinkusb
- name: Download PSP eboot signer
  git: 
    repo: git://github.com/int-0/ebootsigner
    dest: "{{ psptoolchain_tmp_path }}/ebootsigner"
    accept_hostkey: yes
    force: yes

- name: Compile PSP eboot signer
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psptoolchain_tmp_path }}/ebootsigner"
    creates: "{{ psptoolchain_tmp_path }}/ebootsigner/ebootsign"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"

- name: Install PSP eboot signer
  shell: make -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psptoolchain_tmp_path }}/ebootsigner"
    creates: "{{ install_dir }}/bin/ebootsign"
  sudo: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"
