- name: Download insight-{{ psptoolchain_insight_version }}
  get_url:
    url=ftp://sourceware.org/pub/insight/releases/insight-{{ psptoolchain_insight_version }}a.tar.bz2
    dest={{ psptoolchain_tmp_path }}/

- name: Extract insight-{{ psptoolchain_insight_version }}
  unarchive:
    src={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}a.tar.bz2
    dest={{ psptoolchain_tmp_path }}
    copy=no

- name: Apply insight-{{ psptoolchain_insight_version }}-PSP patch
  patch:
    src=insight-{{ psptoolchain_insight_version }}-PSP.patch
    basedir={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}
    strip=1

- name: Create build directory
  file: path={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}/build-{{ target }} state=directory

- name: Configure insight-{{ psptoolchain_insight_version }}
  shell: chdir={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}/build-{{ target }} ../configure --prefix="{{ install_dir }}" --target="{{ target }}" --disable-nls --disable-werror
  environment:
    CFLAGS: -I/opt/local/include
    CPPFLAGS: -I/opt/local/include
    LDFLAGS: -L/opt/local/lib

- name: Compile insight-{{ psptoolchain_insight_version }}
  shell: chdir={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}/build-{{ target }} {{ item }}
  with_items:
    - make -j {{ ansible_processor_vcpus }} clean
    - make -j {{ ansible_processor_vcpus }}

- name: Install insight-{{ psptoolchain_insight_version }}
  sudo: yes
  shell: chdir={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }}/build-{{ target }} make -j {{ ansible_processor_vcpus }} install

- name: Clean insight-{{ psptoolchain_insight_version }}
  file: path={{ psptoolchain_tmp_path }}/insight-{{ psptoolchain_insight_version }} state=absent
