- stat: path=/etc/profile.d/
  register: st

- fail: msg="Remember to add installation directory to your path..."
  when: st.stat.isdir != True

- name: Update environment paths of your systems login scripts!
  sudo: yes
  template:
    src: psptoolchain.sh
    dest: /etc/profile.d/psptoolchain.sh
