- name: Cleanup source directories
  file: path="{{ psptoolchain_tmp_path }}/{{ item }}*" state=absent
  with_items: 
    - binutils-{{ psptoolchain_binutils_version }}
    - gcc-{{ psptoolchain_gcc_version }}
    - gmp-{{ psptoolchain_gmp_version }}
    - mpc-{{ psptoolchain_mpc_version }}
    - mpfr-{{ psptoolchain_mpfr_version }}
    - newlib-{{ psptoolchain_newlib_version }}
    - gbd-{{ psptoolchain_gdb_version }}
    - insight-{{ psptoolchain_insight_version }}
    - pspsdk

- stat: path=/etc/profile.d/
  register: st

- fail: msg="Remember to add installation directory to your path..."
  when: st.stat.isdir != True

- name: Update environment paths of your systems login scripts!
  sudo: yes
  template: src=psptoolchain.sh dest=/etc/profile.d/psptoolchain.sh
