# tasks file for psplinkusb
- name: Download PSP linkusb
  git:
    repo: git://github.com/pspdev/psplinkusb
    dest: "{{ psptoolchain_tmp_path }}/psplinkusb"
    accept_hostkey: yes
    force: yes

- name: Compile PSP linkusb
  shell: "{{ item }}"
  args:
    chdir: "{{ psptoolchain_tmp_path }}/psplinkusb"
    creates: "{{ psptoolchain_tmp_path }}/psplinkusb/pspsh/pspsh"
  with_items:
    - make -f Makefile.clients -j {{ ansible_processor_vcpus }} clean
    - make -f Makefile.clients -j {{ ansible_processor_vcpus }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"

- name: Install PSP linkusb
  shell: make -f Makefile.clients -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psptoolchain_tmp_path }}/psplinkusb"
    creates: "{{ install_dir }}/bin/pspsh"
  sudo: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"
