# tasks file for pspsdk
- name: Download PSP SDK
  git: repo=git://github.com/nabilbendafi/pspsdk
       dest={{ psptoolchain_tmp_path }}/pspsdk
       accept_hostkey=yes

- name: aclocal
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk aclocal -I aclocal

- name: autoheader
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk autoheader

- name: automake
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk automake -a -c --foreign

- name: autoconf
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk autoconf

- name: Configure PSP SDK
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk ./configure --with-pspdev="{{ install_dir }}"
  environment:
    CFLAGS: -I/opt/local/include
    CPPFLAGS: -I/opt/local/include
    LDFLAGS: -L/opt/local/lib

- name: Install PSP SDK (headers only)
  shell: chdir={{ psptoolchain_tmp_path }}/pspsdk {{ item }}
  with_items:
    - make -j {{ ansible_processor_vcpus }} clean
    - make -j {{ ansible_processor_vcpus }} install-data
  sudo: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"

- name: Clean PSP SDK
  file: path={{ psptoolchain_tmp_path }}/pspsdk state=absent
