# tasks file for pspsdk
- name: Download PSP SDK
  git:
    repo: git://github.com/nabilbendafi/pspsdk
    dest: "{{ psptoolchain_tmp_path }}/pspsdk"
    accept_hostkey: yes
    force: yes

- name: aclocal
  shell: aclocal -I aclocal
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ psptoolchain_tmp_path }}/pspsdk/aclocal.m4"

- name: autoheader
  shell: autoheader
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ psptoolchain_tmp_path }}/pspsdk/config.h.in"

- name: automake
  shell: automake -a -c --foreign
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ psptoolchain_tmp_path }}/pspsdk/Makefile.in"

- name: autoconf
  shell: autoconf
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ psptoolchain_tmp_path }}/pspsdk/configure"

- name: Configure PSP SDK
  shell: ./configure --with-pspdev="{{ install_dir }}"
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ psptoolchain_tmp_path }}/pspsdk/config.h"
  environment:
    CFLAGS: -I/opt/local/include
    CPPFLAGS: -I/opt/local/include
    LDFLAGS: -L/opt/local/lib

- name: Install PSP SDK (headers only)
  shell: "{{ item }}"
  args:
    chdir: "{{ psptoolchain_tmp_path }}/pspsdk"
    creates: "{{ install_dir }}/psp/sdk/include/pspsdk.h"
  with_items:
    - make -j {{ ansible_processor_vcpus }} clean
    - make -j {{ ansible_processor_vcpus }} install-data
  sudo: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}/bin"
